new resource `azapi_opration`
Azure/terraform-provider-azapi pull request #150
Opened 2022-07-12 03:59 UTC by ms-henglu

2022-07-12 09:22 UTC, magodo requested changes
Thanks for this PR!
I've taken a look through and left some comments inline, but this is mostly looking good to me 👍

2022-07-12 09:22 UTC, magodo commented on docs/data-sources/azapi_operation.md
> +* `method` - (Optional) Specifies the Http method of the azure resource operation. Allowed values are `POST`, `PATCH`, `GET`, `PUT`, `DELETE`, `CONNECT`, `HEAD`, `OPTIONS` and `TRACE`. Defaults to `P
Should we narrow down the allowed enums for this `method`, as it is only used for query?

2022-07-12 09:22 UTC, magodo commented on internal/clients/resource_client.go
> +	urlPath := fmt.Sprintf("/%s", resourceID)
Is `resourceID` already started with a slash?

2022-07-12 09:22 UTC, magodo commented on internal/clients/resource_client.go
> +		urlPath = fmt.Sprintf("/%s/%s", resourceID, action)
Same here.

2022-07-12 09:22 UTC, magodo commented on internal/clients/resource_client.go
> +	if len(action) != 0 {
I see you use `len()` to check emptyness of a string at a couple of places, why not just `action != ""`?

2022-07-12 09:22 UTC, magodo commented on internal/services/azapi_operation_data_source.go
> +				Default:  "POST",
There is no validation list defined, but the document said there is..

2022-07-12 09:22 UTC, magodo commented on internal/services/azapi_operation_resource.go
> +			}
This can be removed if we define the StateFunc for the `body`?

2022-07-12 09:22 UTC, magodo commented on docs/resources/azapi_operation.md
> +* `method` - (Optional) Specifies the Http method of the azure resource operation. Allowed values are `POST`, `PATCH`, `GET`, `PUT`, `DELETE`, `CONNECT`, `HEAD`, `OPTIONS` and `TRACE`. Defaults to `P
At least the `GET` is not a fit in here.

2022-07-12 09:22 UTC, magodo commented on docs/resources/azapi_operation.md
> +This resource can manage any Azure resource manager resource operation.
Can we emphasize when to use the resource and when to use the data source? From my understanding, the operation that is only used for reading should use the data source.

Also, we shall also add more words in the data source document.

2022-07-13 03:41 UTC, ms-henglu commented
Thanks @magodo for code review, I've addressed these comments, please take another look, thanks!

2022-07-13 05:14 UTC, magodo approved these changes

2022-07-13 05:15 UTC, magodo commented
@ms-henglu LGTM!

2022-07-15 05:45 UTC, merged