feat: support for `when` on resource_action
Azure/terraform-provider-azapi pull request #384
Opened 2023-12-08 13:00 UTC by matt-FFFFFF

2023-12-08 13:43 UTC, matt-FFFFFF commented
Requesting review from @ms-henglu

2023-12-11 04:20 UTC, ms-henglu requested changes
Thanks for taking time to work on this PR!

This PR looks good to me!

But one minor suggestion is that would you please add the new field to the doc: https://github.com/Azure/terraform-provider-azapi/blob/main/docs/resources/azapi_resource_action.md

2023-12-11 10:40 UTC, matt-FFFFFF commented
@ms-henglu have updated docs in 4e7c4a8

2023-12-12 01:50 UTC, ms-henglu approved these changes

2023-12-12 01:50 UTC, merged