feat: use tfplugindocs and update schema for auto doc generation
Azure/terraform-provider-azapi pull request #505
Opened 2024-05-14 12:42 UTC by matt-FFFFFF

## Summary

Now that the provider uses the plugin framework, we can generate documentaiton automatically based on the schema.

To do this we start using tfplugin docs (as recommended by Hashicorp for all these projects).

## Details

- Modify `main.go` to include `go generate` comments
- Update `GNUMakefile` to include `make docs` command and remove legacy website targets
- Move guide content to `templates` to be copied by `tfplugindocs` tool
- Create templates for resources and data sources
- Implemented docstrings package to standardize messaging for common schema attributes
- Added custom template for `data_plane_resource` to add table.

2024-05-14 13:09 UTC, matt-FFFFFF commented
@ms-henglu please can I get your thoughts? If you agree then I will look into the issue with the tflint job.

2024-05-17 02:40 UTC, ms-henglu commented
Thanks @matt-FFFFFF ! This looks great, and makes it much easier to maintain the docs. I'll check this PR later. Thanks!

2024-05-17 22:44 UTC, stemaMSFT commented
Another little minor detail here; @ms-henglu correct me if I'm wrong but I think tons of examples right now set `schema_validation_enabled = false` and also `response_export_values = ["*"]`. Is there a way for us to improve that?

2024-05-20 01:21 UTC, ms-henglu commented
> Another little minor detail here; @ms-henglu correct me if I'm wrong but I think tons of examples right now set `schema_validation_enabled = false` and also `response_export_values = ["*"]`. Is there a way for us to improve that?

Thanks @stemaMSFT , yes, I'll open another PR to improve it.

2024-08-14 04:20 UTC, ms-henglu requested changes
Thanks for the PR! LGTM, just one minor suggestion, once it's addressed I'll merge this PR.

2024-08-14 08:49 UTC, matt-FFFFFF commented on docs/guides/service_principal_client_certificate.md
> -*Passing the encoded certificate bundle directly*
Hi @ms-henglu I have fixe this now - apologies, I missed it somehow

2024-08-14 08:50 UTC, matt-FFFFFF commented
All changes addressed, also updated README to guide on how to generate docs

2024-08-15 02:01 UTC, ms-henglu approved these changes
Thanks! LGTM 💯

2024-08-16 06:02 UTC, merged